import { expect, test } from "@playwright/test";
import { installSkillGroupsFixture } from "./skill-groups.fixture.js";
const acceptance = "Accept Group-Wide Deployment and Ownership Impact";
test("creating another group cannot retain the previously selected group's rules", async ({ page }) => {
  await installSkillGroupsFixture(page);
  await page.goto("/skills-removals-e2e.html?groups=1");
  await page.getByRole("button", { name: "Manage Groups", exact: true }).click();
  await page.getByLabel("New Group Name", { exact: true }).fill("First Group");
  await page.getByRole("button", { name: "Create Group", exact: true }).click();
  await page.getByRole("button", { name: "Add Group Assignment", exact: true }).click();
  await page.getByRole("button", { name: "Add Assignment", exact: true }).click();
  await expect(page.getByRole("button", { name: "Disable Assignment" })).toBeVisible();
  await page.getByLabel("New Group Name", { exact: true }).fill("Second Group");
  await page.getByRole("button", { name: "Create Group", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Second Group", exact: true })).toBeVisible();
  await expect(page.getByText("No group assignments.", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Disable Assignment" })).toHaveCount(0);
});
test("assignment read failure does not masquerade as an empty group", async ({ page }) => {
  await installSkillGroupsFixture(page);
  await page.route("**/api/skill-groups/created/assignments", route => route.fulfill({ status: 503, json: { error: "Assignments temporarily unavailable" } }));
  await page.goto("/skills-removals-e2e.html?groups=1");
  await page.getByRole("button", { name: "Manage Groups", exact: true }).click();
  await page.getByLabel("New Group Name", { exact: true }).fill("Read Failure");
  await page.getByRole("button", { name: "Create Group", exact: true }).click();
  await expect(page.getByRole("alert")).toContainText("Assignments temporarily unavailable");
  await expect(page.getByRole("button", { name: "Add Group Assignment", exact: true })).toBeDisabled();
  await expect(page.getByText("No group assignments.", { exact: true })).toHaveCount(0);
});
for (const width of [1280, 320]) for (const theme of ["dark", "light"]) {
  test(`group membership and inherited rules at ${width} in ${theme}`, async ({ page }, info) => {
    const fixture = await installSkillGroupsFixture(page);
    await page.setViewportSize({ width, height: 900 });
    await page.goto("/skills-removals-e2e.html?groups=1");
    await page.evaluate(theme => { document.documentElement.dataset.theme = theme; }, theme);
    await page.getByRole("button", { name: "Manage Groups", exact: true }).click();
    await page.getByLabel("New Group Name", { exact: true }).fill("Review Team");
    await page.getByRole("button", { name: "Create Group", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Review Team", exact: true })).toBeVisible();
    await page.getByRole("button", { name: /^Skill to Add:/ }).click();
    await page.getByRole("option", { name: "code-review", exact: true }).click();
    await expect(page.getByRole("button", { name: "Add Member", exact: true })).toBeDisabled();
    await page.getByRole("checkbox", { name: acceptance }).check();
    await page.getByRole("button", { name: "Add Member", exact: true }).click();
    await expect(page.getByRole("button", { name: "Remove code-review from Group" })).toBeVisible();
    await page.getByRole("button", { name: "Add Group Assignment", exact: true }).click();
    await page.getByRole("button", { name: /^Machine:/ }).click();
    await page.getByRole("option", { name: "Build Machine" }).click();
    await page.getByRole("button", { name: /^Agents:/ }).click();
    await page.getByRole("option", { name: "Claude", exact: true }).click();
    await page.getByRole("button", { name: "Add Assignment", exact: true }).click();
    await expect(page.getByRole("button", { name: "Disable Assignment" })).toBeVisible();
    expect(fixture.writes.find(write => write.path.endsWith("/assignments"))?.body).toEqual({ scopeKind: "runner", runnerId: "runner-1", agentSelector: { kind: "agent", agentId: "claude" }, invocation: "agent" });
    await page.screenshot({ path: info.outputPath(`groups-${width}-${theme}.png`), fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
    await page.getByRole("checkbox", { name: acceptance }).check();
    await page.getByRole("button", { name: "Disable Assignment" }).click();
    await expect(page.getByRole("button", { name: "Enable Assignment" })).toBeVisible();
    await page.getByRole("checkbox", { name: acceptance }).check();
    await page.getByRole("button", { name: "Enable Assignment" }).click();
    await page.getByRole("button", { name: "Close", exact: true }).last().click();
    await page.getByRole("button", { name: /code-review/i }).click();
    await expect(page.getByRole("region", { name: "Inherited Assignments" })).toContainText("Build Machine · Claude · Agent Invocable · Enabled");
    await page.screenshot({ path: info.outputPath(`inherited-${width}-${theme}.png`), fullPage: true });
    await page.getByRole("button", { name: "Manage Group Assignments", exact: true }).click();
    await page.getByRole("button", { name: /^Group:/ }).click();
    await page.getByRole("option", { name: "Review Team", exact: true }).click();
    await page.getByRole("checkbox", { name: acceptance }).check();
    await page.getByRole("button", { name: "Delete Group and Its Assignments" }).click();
    await expect(page.getByRole("heading", { name: "Review Team", exact: true })).toHaveCount(0);
    await expect(page.getByRole("alert")).toHaveCount(0);
    await page.getByRole("button", { name: "Close", exact: true }).last().click();
    await expect(page.getByRole("region", { name: "Inherited Assignments" })).toHaveCount(0);
    await expect(page.getByRole("button", { name: /code-review/i })).toBeVisible();
  });
}
test("legacy conversion is explicit and discloses permanent ownership", async ({ page }) => {
  const { writes } = await installSkillGroupsFixture(page);
  await page.goto("/skills-removals-e2e.html?groups=1");
  await page.getByRole("button", { name: "Manage Groups", exact: true }).click();
  await page.getByRole("button", { name: /^Group:/ }).click();
  await page.getByRole("option", { name: "Legacy Tools" }).click();
  await expect(page.getByText(/Conversion permanently assigns ownership/)).toBeVisible();
  await expect(page.getByText("Resulting ownership: Organization demo-org.")).toBeVisible();
  await expect(page.getByRole("button", { name: "Convert Group", exact: true })).toBeDisabled();
  expect(writes).toHaveLength(0);
  await page.getByRole("checkbox", { name: acceptance }).check();
  await page.getByRole("button", { name: "Convert Group", exact: true }).click();
  await expect(page.getByRole("button", { name: "Add Group Assignment", exact: true })).toBeEnabled();
  await expect(page.getByRole("button", { name: "Convert Group", exact: true })).toHaveCount(0);
});
test("failed conversion preserves the legacy group and surfaces the server error", async ({ page }) => {
  await installSkillGroupsFixture(page);
  await page.route("**/api/skill-groups/legacy/convert", route => route.fulfill({ status: 409, json: { error: "Members have different ownership. No changes saved." } }));
  await page.goto("/skills-removals-e2e.html?groups=1");
  await page.getByRole("button", { name: "Manage Groups", exact: true }).click();
  await page.getByRole("button", { name: /^Group:/ }).click();
  await page.getByRole("option", { name: "Legacy Tools" }).click();
  await page.getByRole("checkbox", { name: acceptance }).check();
  await page.getByRole("button", { name: "Convert Group", exact: true }).click();
  await expect(page.getByRole("alert")).toContainText("No changes saved");
  await expect(page.getByRole("button", { name: "Add Group Assignment", exact: true })).toHaveCount(0);
});
