import { createHash } from "node:crypto";
import type { GithubIssueClosureSnapshot } from "@wollipog/protocol";
import { isTerminal } from "@wollipog/protocol";
import type { ControlPlaneDb } from "./db.js";

const bounded = (value: unknown, max: number): value is string => typeof value === "string" &&
  value.length > 0 && value.length <= max && !value.includes("\0");
const sha = (value: unknown): value is string => typeof value === "string" && /^[0-9a-f]{64}$/u.test(value);
const record = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);

/** Canonical, bounded snapshot used for hashing and recovery. Inputs are generated by the server,
 * not accepted as a way for an agent to assert current GitHub or child evidence. */
export function normalizeIssueClosureSnapshot(value: Record<string, unknown>): GithubIssueClosureSnapshot | null {
  if (!bounded(value.repository, 256) || !/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/u.test(value.repository) ||
      !Number.isSafeInteger(value.issue) || (value.issue as number) < 1 ||
      !bounded(value.title, 1024) || value.url !== `https://github.com/${value.repository}/issues/${value.issue}` ||
      !sha(value.forgeDigest) || !["completed", "not_planned"].includes(value.reason as string) ||
      !bounded(value.explanation, 4000) || !Array.isArray(value.evidence) || value.evidence.length < 1 ||
      value.evidence.length > 32 || value.evidence.some((item) => !bounded(item, 4000)) ||
      (value.comment !== undefined && !bounded(value.comment, 65_536)) ||
      !Array.isArray(value.openPullRequests) || value.openPullRequests.length > 100 ||
      !Array.isArray(value.activeChildren) || value.activeChildren.length > 100) return null;
  const openPullRequests: GithubIssueClosureSnapshot["openPullRequests"] = [];
  for (const pr of value.openPullRequests) {
    if (!record(pr) || !Number.isSafeInteger(pr.number) || (pr.number as number) < 1 ||
        !bounded(pr.title, 1024) || pr.url !== `https://github.com/${value.repository}/pull/${pr.number}` ||
        typeof pr.headSha !== "string" || !/^[0-9a-f]{40}$/u.test(pr.headSha)) return null;
    openPullRequests.push({ number: pr.number as number, title: pr.title, url: pr.url as string, headSha: pr.headSha });
  }
  const activeChildren: GithubIssueClosureSnapshot["activeChildren"] = [];
  for (const child of value.activeChildren) {
    if (!record(child) || !bounded(child.sessionId, 256) || !bounded(child.title, 1024) || !sha(child.assignmentDigest)) return null;
    activeChildren.push({ sessionId: child.sessionId, title: child.title, assignmentDigest: child.assignmentDigest });
  }
  if (value.scopeRevision !== undefined && (!Number.isSafeInteger(value.scopeRevision) || (value.scopeRevision as number) < 1)) return null;
  return { ...(value.scopeRevision === undefined ? {} : { scopeRevision: value.scopeRevision as number }), category: "issue_closure", repository: value.repository, issue: value.issue as number,
    title: value.title, url: value.url as string, forgeDigest: value.forgeDigest,
    reason: value.reason as GithubIssueClosureSnapshot["reason"], explanation: value.explanation,
    evidence: [...value.evidence] as string[], ...(value.comment === undefined ? {} : { comment: value.comment as string }),
    openPullRequests, activeChildren };
}

/** Any live campaign child can still hold related work. Include it conservatively: a task can
 * move between issues in steering history, and a later "continue" prompt is not proof it is unrelated. */
export function issueClosureActiveChildren(db: ControlPlaneDb, sessionId: string) {
  return db.campaignDescendantIds(sessionId).flatMap((id) => {
    const child = db.getSession(id);
    if (!child || isTerminal(child.status) || child.archived) return [];
    const assignment = db.initialUserMessageText(id);
    const state = db.issueClosureAssignmentState(id);
    const prompts = [...(child.queued ?? []), ...(child.pendingPrompts ?? [])];
    return [{ sessionId: id, title: child.title,
      assignmentDigest: createHash("sha256").update(JSON.stringify({
        assignment, state, prompts, parentSessionId: child.parentSessionId, worktreePath: child.worktreePath,
        pending: db.unconsumedWorkflowDecisionsForSession(id).map((decision) => ({
          occurrenceId: decision.occurrenceId, digest: decision.resourceDigest, status: decision.status,
        })),
      })).digest("hex") }];
  });
}
